import { Inter } from "next/font/google";
import "./globals.css";
import DisplayProvider from "./context/DisplayContext";
import Navbar from "@/components/Navbar";
import ThemeProvider from "./context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kanban board | By Atif",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <DisplayProvider>
            <main>
              <Navbar />
              {children}
            </main>
          </DisplayProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
