import { Inter } from "next/font/google";
import "./globals.css";
import DisplayProvider from "./context/DisplayContext";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DisplayProvider>
          <main>
            <Navbar />
            {children}
          </main>
        </DisplayProvider>
      </body>
    </html>
  );
}
